title: NutriCheck
description: Анализ питания студентов
baseurl: "/nutricheck"
url: "https://MagisterGudvin.github.io"
exclude:
  - worker/
  - tools/
  - node_modules/
  - README.md
include:
  - books/
